# Generated by Django 3.1.4 on 2024-09-04 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task1Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('right', models.PositiveIntegerField(default=0, verbose_name='Number of right answers')),
                ('wrong', models.PositiveIntegerField(default=0, verbose_name='Number of wrong answers')),
                ('end', models.DateTimeField(blank=True, editable=False, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('duration', models.DurationField(null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['duration', '-wrong'],
            },
        ),
        migrations.CreateModel(
            name='PackmolPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chebi', models.CharField(max_length=30)),
                ('cell', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=10)),
                ('mol', models.TextField()),
                ('score', models.FloatField(null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='packmols', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
