# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1play',
            name='right',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of right answers'),
        ),
        migrations.AlterField(
            model_name='task1play',
            name='wrong',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of wrong answers'),
        ),
    ]
