# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160904_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1play',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
